### ISSUE TITLE
在IOS8.3 无法发送POST请求,IOS 10 11 都没问题

### ISSUE THREAD

**Issue by zenggang** [QianKun-HanLin/HLNetworking#1]
---------HLURLResult Start---------
Status : HLURLResultStatusErrorNotReachable
Object : (null)
Error : Error Domain=NSURLErrorDomain Code=-1002 "网络不可用，请稍后重试, http://xxx.com 无法访问" UserInfo=0x174074140 {NSLocalizedDescription=网络不可用，请稍后重试, http://xxx.com 无法访问}

**Comment by CodeWeaver13** [comment]
iOS8下SCNetworkReachabilityRef有时候会不好使，可以考虑在iOS8时禁止`HLNetworkEngine.m`中164-182行的代码执行
